---
# tasks for ca java based apps
#

- name: user - add tomcat user to arcot group
  user:
    name: tomcat
    append: yes
    group: arcot

- name: template - arcot env script in profile.d
  template:
    src: arwfenv.profile.sh.j2
    dest: /etc/profile.d/arwfenv.sh
    mode: 0755
    owner: root
    group: root


- name: add arcot env vars to tomcat systemd config file
  blockinfile:
    path: "/etc/sysconfig/tomcat"
    state: present
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    backup: yes
    insertafter: EOF
    block: |
           LD_LIBRARY_PATH={{ arcot_home }}/odbc64v80/lib:{{ arcot_home }}/sbin:{{ arcot_home }}/lib:{{ arcot_home }}/bin:{{ arcot_home }}/sdk/server/plugin/c/lib:{{ java_home }}/jre/bin
           ARCOT_HOME={{ arcot_home }}
           PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/bin:/opt/puppetlabs/bin:{{ catalina_home }}/bin:{{ java_home }}/bin:/root/bin:{{ java_home }}/bin
  notify: restart tomcat
