---
become: true
vars_files:
  - "group_vars/{{ lookup('env', 'HOSTNAME') | regex_search('paychex|pxlabus') }}.yml"

- hosts: rsk-app
  roles:
    - ca-adv-auth

- hosts: rsk-web
  roles:
    - tomcat9
    - ca-adv-auth
    - ca-web
