---

- name: download risk auth zip
  get_url:
    url: "{{ arcot_db_upgrade_zip_url }}"
    dest: "/tmp/{{ arcot_db_upgrade_zip_url | basename }}"
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_user }}"
    mode: 0755
  
- name: make upgrade package dir
  file:
    path: "{{ arcot_home }}/patches/{{ arcot_db_upgrade_zip_dir }}"
    state: directory
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_user }}"
    mode: 0755

- name: download and unzip db upgrade package
  unarchive:
    src: "/tmp/{{ arcot_db_upgrade_zip_dir }}.zip"
    dest: "{{ arcot_home }}/patches/"
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_user }}"
    mode: 0755
    remote_src: True

- name: execute upgrade
  command: java -jar aa-upgrade-tool.jar
  args:
    chdir: "{{ arcot_home }}/patches/{{ arcot_db_upgrade_zip_dir }}/{{ arcot_db_upgrade_AA_dir }}"
  register: upgrade_output
  failed_when: '"100% DONE" not in upgrade_output.stdout'

    