---
# this grouping of  tasks receives a download location for a zipped patch and applies it to the host

- name: check if patch is installed
  stat:
    path: "{{ arcot_home }}/patches/{{ arcot_patch_url | basename }}"
  register: installed


- name: install patch
  block:
    # name: shutdown stack
    - import_tasks: powerdown_app_stack.yml
      when: facter_payx_advauthrole == "rsk-app"
      notify: start stack

    - name: dir - create CA dir
      file:
        name: "{{ arcot_home }}/patches/{{ arcot_patch_url | basename }}"
        state: directory
        owner: "{{ arcot_user }}"
        group: "{{ arcot_user }}"
        mode: 0755

    - name: download patch
      get_url:
        url: "{{ arcot_patch_url }}"
        dest: "{{ arcot_home }}/patches/{{ arcot_patch_url | basename }}"
        owner: "{{ arcot_user }}"
        group: "{{ arcot_user }}"
        mode: 0755

    - name: unzip patch
      unarchive:
        src: "{{ arcot_home }}/patches/{{ arcot_patch_url | basename}}/{{ arcot_patch_url | basename }}"
        dest: "{{ arcot_home }}/patches/{{ arcot_patch_url | basename }}"
        owner: "{{ arcot_user }}"
        group: "{{ arcot_user }}"
        mode: 0755
        remote_src: yes

    - name: "install patch {{ arcot_patch_url | basename }}"
      shell: "./install.sh"
      args:
        chdir: "{{ arcot_home }}/patches/{{ arcot_patch_url | basename }}"
      environment:
        ARCOT_HOME: "{{ arcot_home }}"
      become_user: "{{ arcot_user }}"
  when: installed.stat.exists == false


  # download adapter patch

- name: download adapter patch
  get_url:
    url: "{{ arcot_adapter_patch_url }}"
    dest: "{{ arcot_home }}/patches/{{ arcot_adapter_patch_url | basename }}"
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755

- name: unzip patch
  unarchive:
    src: "{{ arcot_home }}/patches/{{ arcot_adapter_patch_url | basename}}/{{ arcot_adapter_patch_url | basename }}"
    dest: "{{ arcot_home }}/patches/{{ arcot_adapter_patch_url | basename }}"
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755
    remote_src: yes
  # unzip
  # remove old state manager
  # install new state manager