---

- name: install pexpect for adapter installation
  import_tasks: pexpect.yml

- name: download strong auth zip that contains adapter
  get_url:
    url: "{{ arcot_strong_url }}"
    dest: "{{ arcot_home }}"
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_group }}"
    mode: 0755

- name: unzip strong auth that contains adapter
  unarchive:
    src: "{{ arcot_home }}/{{ arcot_strong_url | basename }}"
    dest: "{{ arcot_home }}"
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_group }}"
    mode: 0755
    remote_src: yes
    creates: "{{ arcot_home }}/{{ arcot_strong_zip_parent_dir }}"

- name: "set {{ arcot_adapter_install_home }} permissions as workaround for installer issues"
  file:
    path: "{{ arcot_adapter_install_home }}"
    state: directory
    mode: 0777


- name: install ca adapter
  expect:
    command: "{{ arcot_home }}/{{ arcot_strong_zip_parent_dir }}/CA-Adapter/{{ arcot_adapter_installer }} -jvmxmx 1500m"
    responses:
        'Install Location': '{{ arcot_adapter_install_home }}'
        'PRESS <ENTER> TO CONTINUE': "\n"
        'PRESS <ENTER> TO INSTALL': "\n"
        'DO YOU ACCEPT THE TERMS OF THIS LICENSE AGREEMENT': "Y"
        'ENTER THE NUMBER FOR THE INSTALL SET': "\n"
        'TO EXIT THE INSTALLER': "\n"
        'PRESS <ENTER> TO EXIT THE INSTALLER:': "\n"
        '  2- /opt/': '2'
  become_user: "{{ arcot_os_user }}"
  become: true
  register: cmd_result
  failed_when: '"Installation Complete" not in cmd_result.stdout'

- name: "reset {{ arcot_adapter_install_home }} permissions as workaround for installer issues"
  file:
    path: "{{ arcot_adapter_install_home }}"
    state: directory
    mode: 0755

      