---

- name: check for strong auth install
  stat:
    path: "{{ arcot_home }}/{{ arcot_strong_url | basename }}"
  register: str_installed

- name: check for risk auth install
  stat:
    path: "{{ arcot_home }}/{{ arcot_risk_url | basename }}"
  register: rsk_installed  

 # check if adapter is installed
- name: check for adapter install (statemanager)
  stat:
    path: "{{ arcot_home }}/adapterStateManager"
  register: adapter_installed  