---
# tasks file for advanced auth
#

- name: Asserts
  import_tasks: asserts.yml

- name: group - arcot
  group:
    name: arcot
    state: present

- name: user - create arcot user
  user:
    name: arcot
    group: arcot
    shell: /bin/bash
    password: "{{ arcot_os_password }}"

- name: dir - create CA dir
  file:
    name: "{{ arcot_home }}"
    state: directory
    owner: arcot
    group: arcot
    mode: 0755

- name: install strong auth
  import_tasks: strong_auth.yml
  when: str_installed.stat.exists == false

- name: install ca adapter
  import_tasks: adapter.yml
  when: arcot_adapter_install and adapter_installed.stat.exists == false

- name: install risk auth
  import_tasks: risk_auth.yml
  when: rsk_installed.stat.exists == false


- name: install web services
  import_tasks: java_apps.yml
  when: arcot_web_services

- name: install 9.0.02 patches
  import_tasks: 9.02_patch.yml
  when: arcot_patch_update


# - name: execute jar for old db upgrade
#   import_tasks: 3.x_db_upgrade.yml
#   when: arcot_3.x_db_upgrade
#   run_once: true
