- name: stop webfort
  shell: "systemctl daemon-reload && systemctl stop webfortserver"

- name: stop riskfort
  shell: "systemctl daemon-reload && systemctl stop riskfortserver && systemctl stop casemanagementserver"

- name: stop tomcat
  command: systemctl stop tomcat
