---
# handlers file for tomcat
#

- name: start stack
  shell: "systemctl daemon-reload && systemctl enable webfortserver && systemctl start webfortserver && systemctl daemon-reload && systemctl enable riskfortserver && systemctl start riskfortserver && systemctl enable casemanagementserver && systemctl start casemanagementserver"
