---

- name: check for download
  stat:
    path: "{{ arcot_home }}/{{ arcot_strong_url | basename }}"
  register: str_installed

- name: check for download
  stat:
    path: "{{ arcot_home }}/{{ arcot_risk_url | basename }}"
  register: rsk_installed