---
# tasks file for tomcat
#

- name: group - create arcot_user group
  group:
    name: "{{ arcot_user }}"
    state: present

- name: user - create arcot_user user
  user:
    name: "{{ arcot_user }}"
    shell: /bin/bash
    password: "{{ arcot_password }}"

- name: dir - create CA dir
  file:
    name: "{{ arcot_home }}"
    state: directory
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755

- name: template - tomcat.service for systemd
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: 0755
  notify: restart tomcat

- name: template - sysconfig tomcat env vars for systemd
  template:
    src: sysconfig.tomcat.j2
    dest: /etc/sysconfig/tomcat
    owner: root
    group: root
    mode: 0755
