---
# tasks file for tomcat
#

- name: group - create arcot_user group
  group:
    name: "{{ arcot_user }}"
    state: present

- name: user - create arcot_user user
  user:
    name: "{{ arcot_user }}"
    shell: /bin/bash
    password: "{{ arcot_password }}"

- name: user - add tomcat user to arcot group
  user:
    name: tomcat
    append: yes
    group: arcot

- name: dir - create CA dir
  file:
    name: "{{ arcot_home }}"
    state: directory
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755

- name: deploy systemd services and sysconfig env vars
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: "restart {{ item.handler }}"
  with_items:
    - { src: 'tomcat.service.j2', dest: '/etc/systemd/system/tomcat.service', handler: 'tomcat', mode: '0664' }
    - { src: 'sysconfig.arcot.j2', dest: '/etc/sysconfig/arcot', handler: 'systemd', mode: '0644' }
#    - { src: 'sysconfig.tomcat.j2', dest: '/etc/sysconfig/tomcat', handler: 'tomcat', mode: '0644' }

blockinfile:
  path: "/etc/sysconfig/tomcat"
  state: present
  marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  backup: yes
  insertafter: EOF
  block: |
         "LD_LIBRARY_PATH={{ arcot_home }}/odbc64v80/lib:{{ arcot_home }}/sbin:{{ arcot_home }}/lib:{{ arcot_home }}/bin:{{ arcot_home }}/sdk/server/plugin/c/lib:{{ java_home }}/jre/bin
         ARCOT_HOME={{ arcot_home }}
         PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/bin:/opt/puppetlabs/bin:{{ catalina_home }}/bin:{{ java_home }}/bin:/root/bin:{{ java_home }}/bin"
notify: restart tomcat

# - name: template - tomcat.service for systemd
#   template:
#     src: tomcat.service.j2
#     dest: /etc/systemd/system/tomcat.service
#     owner: root
#     group: root
#     mode: 0755
#   notify: restart tomcat

# - name: template - sysconfig tomcat env vars for systemd
#   template:
#     src: sysconfig.tomcat.j2
#     dest: /etc/sysconfig/tomcat
#     owner: root
#     group: root
#     mode: 0755

# - name: template - sysconfig arcot env vars for systemd
#   template:
#     src: sysconfig.arcot.j2
#     dest: /etc/sysconfig/arcot
#     owner: root
#     group: root
#     mode: 0755
