---
# tasks file for tomcat
#

- name: user - create arcot user
  user:
    name: arcot
    group: arcot
    shell: /bin/bash
    password: "{{ arcot_password }}"

- name: user - add tomcat user to arcot group
  user:
    name: tomcat
    append: yes
    group: arcot

- name: dir - create CA dir
  file:
    name: "{{ arcot_home }}"
    state: directory
    owner: arcot
    group: arcot
    mode: 0755

- name: template - arcot env script in profile.d
  template:
    src: arwfenv.profile.sh.j2
    dest: /etc/profile.d/arwfenv.sh
    mode: 0755
    owner: root
    group: root

- name: deploy systemd services and sysconfig env vars
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  notify: "restart {{ item.handler }}"
  with_items:
    - { src: 'tomcat.service.j2', dest: '/etc/systemd/system/tomcat.service', handler: 'tomcat', mode: '0664' }

- name: add arcot env vars to tomcat systemd config file
  blockinfile:
    path: "/etc/sysconfig/tomcat"
    state: present
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    backup: yes
    insertafter: EOF
    block: |
           LD_LIBRARY_PATH={{ arcot_home }}/odbc64v80/lib:{{ arcot_home }}/sbin:{{ arcot_home }}/lib:{{ arcot_home }}/bin:{{ arcot_home }}/sdk/server/plugin/c/lib:{{ java_home }}/jre/bin
           ARCOT_HOME={{ arcot_home }}
           PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/bin:/opt/puppetlabs/bin:{{ catalina_home }}/bin:{{ java_home }}/bin:/root/bin:{{ java_home }}/bin
  notify: restart tomcat
