---
# tasks file for advanced auth
#

- name: Asserts
  import_tasks: asserts.yml

- name: group - arcot
  group:
    name: arcot
    state: present

- name: user - create arcot user
  user:
    name: arcot
    group: arcot
    shell: /bin/bash
    password: "{{ arcot_os_password }}"

- name: dir - create CA dir
  file:
    name: "{{ arcot_home }}"
    state: directory
    owner: arcot
    group: arcot
    mode: 0755

- name: install strong auth
  import_tasks: strong_auth.yml
  when: str_installed.stat.exists == false

- name: install risk auth
  import_tasks: risk_auth.yml
  when: str_installed.stat.exists == false

# - name: execute jar for old db upgrade
#   import_tasks: older_db_upgrade.yml
#   when: older_db_upgrade


- name: install web services
  import_tasks: java_apps.yml
  when: web_services

# install patch 9.0.02
- import_tasks: patch.yml
  vars:
    patch_url: http://repoman.paychex.com/packages/CA/advanced_auth/9.0.02/CA-AdvancedAuthentication-Patch-9.0.02-Linux.zip
