# this grouping of  tasks receives a download location for a zipped patch and applies it to the host

- name: check if patch is installed
  stat: "{{ arcot_home }}/{{ patch_url | basename }}"
  register: installed


- name: install patch
  block:
    - name: dir - create CA dir
      file:
        name: "{{ arcot_home }}/{{ patch_url | basename }}"
        state: directory
        owner: arcot
        group: arcot
        mode: 0755

    - name: download patch

    - name: unzip patch

    - name: install patch


  when: installed.stat.exists == false
