---

- name: download risk auth zip
  get_url:
    url: "{{ rsk_auth_install_url }}"
    dest: "{{ arcot_home }}"
    owner: arcot
    group: arcot
    mode: 0755

- name: unzip risk auth
  unarchive:
    src: "{{ arcot_home }}/{{ rsk_auth_install_url | basename }}"
    dest: "{{ arcot_home }}"
    owner: arcot
    group: arcot
    mode: 0755
    remote_src: yes

- name: template - riskfort
  vars:
    app: riskfortserver
  template:
    src: init.d.j2
    dest: "/etc/init.d/{{ app }}"
    owner: root
    group: root
    mode: 0755
  notify: start stack


- name: template - casemgmt
  vars:
    app: casemanagementserver
  template:
    src: init.d.j2
    dest: "/etc/init.d/{{ app }}"
    owner: root
    group: root
    mode: 0755
  notify: start stack

- name: template - risk silent install file
  template:
    src: installer.properties.j2
    dest: "/tmp/riskauth-installer.properties"
    mode: 0755
    owner: arcot
    group: arcot

- name: run silent installer for risk auth
  shell: "./{{ rsk_bin }} -f /tmp/riskauth-installer.properties -i silent"
  args:
    chdir: "{{ arcot_home }}/{{ rsk_zip_dir }}"
    creates: "{{ arcot_home }}/riskauth-installer.properties"
  environment:
    ARCOT_HOME: "{{ arcot_home }}"
  become_user: "{{ arcot_user }}"
  notify: start stack