---

- name: template - arcot env script in profile.d
  template:
    src: arwfenv.profile.sh.j2
    dest: /etc/profile.d/arwfenv.sh
    mode: 0755
    owner: root
    group: root

- name: download strong auth zip
  get_url:
    url: "{{ arcot_strong_url }}"
    dest: "{{ arcot_home }}"
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_group }}"
    mode: 0755

- name: unzip strong auth
  unarchive:
    src: "{{ arcot_home }}/{{ arcot_strong_url | basename }}"
    dest: "{{ arcot_home }}"
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_group }}"
    mode: 0755
    remote_src: yes

- name: template - strong auth silent install file
  template:
    src: installer.properties.j2
    dest: "/tmp/strongauth-installer.properties"
    mode: 0755
    owner: "{{ arcot_os_user }}"
    group: "{{ arcot_os_group }}"

- name: run silent installer for strong auth
  shell: "./{{ arcot_strong_installer }} -f /tmp/strongauth-installer.properties -i silent"
  args:
    chdir: "{{ arcot_home }}/{{ arcot_strong_zip_parent_dir }}"
    creates: "{{ arcot_home }}/strongauth-installer.properties"
  environment:
    ARCOT_HOME: "{{ arcot_home }}"
  become_user: "{{ arcot_os_user }}"
  become: true
  notify: start stack

- name: template - webfort
  vars:
    app: webfortserver
  template:
    src: init.d.j2
    dest: "/etc/init.d/{{ app }}"
    owner: root
    group: root
    mode: 0755
  notify: start stack