---

- name: deploy arcot admin
  copy:
    remote_src: yes
    src: "{{ arcot_home }}/java/webapps/arcotadmin.war"
    dest: "{{ catalina_home }}/webapps"
    owner: tomcat
    group: tomcat
    mode: 0755
  notify: restart tomcat

- name: deploy sample app
  copy:
    remote_src: yes
    src: "{{ arcot_home }}/samples/java/ca-riskauth-sample-application.war"
    dest: "{{ catalina_home }}/webapps"
    owner: tomcat
    group: tomcat
    mode: 0755
  when: sample_app == 'yes'
  notify: restart tomcat
