---
# tasks file for tomcat
#

- name: dir - create CA dir
  file:
    name: "{{ arcot_home }}"
    state: directory
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755

- name: download risk auth zip
  get_url:
    url: "{{ rsk_auth_install_url }}"
    dest: "{{ arcot_home }}"
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755

- name: unzip risk auth
  unarchive:
    src: "{{ arcot_home }}/{{ rsk_auth_install_url | basename }}"
    dest: "{{ arcot_home }}"
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"
    mode: 0755
    remote_src: yes

##################################################################
#### install starts here #########################################

- name: deploy systemd services and sysconfig env vars
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  notify: "restart {{ item.handler }}"
  with_items:
    - { src: 'riskauth.service.j2', dest: '/etc/systemd/system/riskauth.service', handler: 'systemd' }
    - { src: 'casemgmt.service.j2', dest: '/etc/systemd/system/casemgmt.service', handler: 'systemd' }

- name: template - strong risk silent install file
  template:
    src: rsk.installer.properties.j2
    dest: "/tmp/riskauth-installer.properties"
    mode: 0755
    owner: "{{ arcot_user }}"
    group: "{{ arcot_user }}"

- name: run silent installer for strong auth
  shell: "./{{ rsk_bin }} -f /tmp/riskauth-installer.properties -i silent"
  args:
    chdir: "{{ arcot_home }}/{{ rsk_zip_dir }}"
    creates: "{{ arcot_home }}/riskauth-installer.properties"
  when: risk_auth_install == "yes"
  environment:
    ARCOT_HOME: "{{ arcot_home }}"
  become_user: "{{ arcot_user }}"

- name: deploy sample app
  copy:
    remote_src: yes
    src: "{{ arcot_home }}/samples/java/ca-riskauth-sample-application.war"
    dest: "{{ catalina_home }}/webapps"
    owner: tomcat
    group: tomcat
    mode: 0755
  when: sample_app == 'yes'
  notify: restart tomcat
