---
# tasks file for tomcat
#



- name: group - create tomcat group
  group:
    name: tomcat
    gid: 101
    state: present

- name: user - create tomcat user
  user:
    name: tomcat
    uid: 101
    shell: /bin/bash
    password: $1$21575$iBYQIOSnpf7Ac4lHoAVgb.

# may be unnecessary since systemd launches the app
- name: template - tomcat env script in profile.d
  template:
    src: tomcat.profile.sh.j2
    dest: /etc/profile.d/tomcat.profile.sh
    mode: 0755
    owner: root
    group: root

- name: template - tomcat.service for systemd
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: 0644

- name: template - sysconfig tomcat env vars for systemd
  template:
    src: sysconfig.tomcat.j2
    dest: /etc/sysconfig/tomcat
    owner: root
    group: root
    mode: 0755

- name: dir - create tomcat dir
  file:
    name: "{{ catalina_home }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755

- name: download tomcat tar
  get_url:
    url: "{{ tomcat_install_url }}"
    dest: "{{ catalina_home }}"
    owner: tomcat
    group: tomcat
    mode: 0755
  notify: restart tomcat

- name: unzip tomcat
  unarchive:
    src: "{{ catalina_home }}/{{ tomcat_install_url | basename }}"
    dest: "{{ catalina_home }}"
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts:
      - --strip-components=1
  notify: restart tomcat

- name: start and enable tomcat
  systemd:
    name: tomcat.service
    enabled: true
    state: started
