---

- hosts: rsk-web
  become: True
  run_once: True
  vars_files:
    - ../roles/ca-adv-auth/defaults/main.yml
  vars:
    - db_upgrade_zip_dir: GEN500000000000104
    - db_upgrade_AA_dir: AA-Upgrade-6.2.x-7.x-2.2.6-above-3.x-to-9.0
    - db_upgrade_zip_url: http://repoman.paychex.com/packages/CA/advanced_auth/9.0/GEN500000000000104.zip

  tasks:
    # ENSURE ONLY RUN ONCE
    - name: download risk auth zip
      get_url:
        url: "{{ db_upgrade_zip_url }}"
        dest: "/tmp/{{ db_upgrade_zip_url | basename }}"
        owner: "{{ arcot_os_user }}"
        group: "{{ arcot_os_user }}"
        mode: 0755
      
    - name: make upgrade package dir
      file:
        path: "{{ arcot_home }}/{{ db_upgrade_zip_dir }}"
        state: directory
        owner: "{{ arcot_os_user }}"
        group: "{{ arcot_os_user }}"
        mode: 0755

    - name: download and unzip db upgrade package
      unarchive:
        src: "/tmp/{{ db_upgrade_zip_dir }}.zip"
        dest: "{{ arcot_home }}"
        owner: "{{ arcot_os_user }}"
        group: "{{ arcot_os_user }}"
        mode: 0755
        remote_src: True

    - name: execute upgrade
      command: java -jar aa-upgrade-tool.jar
      args:
        chdir: "{{ arcot_home }}/{{ db_upgrade_zip_dir }}/{{ db_upgrade_AA_dir }}"
      register: upgrade_output
      failed_when: '"100% DONE" not in upgrade_output.stdout'
    
    